### ISSUE TITLE
Android app crash on authorizeEventStore

### ISSUE THREAD

**Issue by gourav-singhal** [wmcmahan/react-native-calendar-events#107]
Hi 

The android app crashes with following error log:-

Fatal Exception: java.lang.RuntimeException: Unable to resume activity {sh.mobile.vh/sh.mobile.vh.MainActivity}: java.lang.NullPointerException: Attempt to invoke interface method 'void com.facebook.react.bridge.Callback.invoke(java.lang.Object[])' on a null object reference
       at android.app.ActivityThread.performResumeActivity(ActivityThread.java:3430)
       at android.app.ActivityThread.handleResumeActivity(ActivityThread.java:3470)
       at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1528)
       at android.os.Handler.dispatchMessage(Handler.java:102)
       at android.os.Looper.loop(Looper.java:154)
       at android.app.ActivityThread.main(ActivityThread.java:6121)
       at java.lang.reflect.Method.invoke(Method.java)
       at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:889)
       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:779)
Caused by java.lang.NullPointerException: Attempt to invoke interface method 'void com.facebook.react.bridge.Callback.invoke(java.lang.Object[])' on a null object reference
       at com.facebook.react.modules.permissions.PermissionsModule.onRequestPermissionsResult(PermissionsModule.java:207)
       at com.facebook.react.ReactActivityDelegate$1.invoke(ReactActivityDelegate.java:211)
       at com.facebook.react.ReactActivityDelegate.onResume(ReactActivityDelegate.java:131)
       at com.facebook.react.ReactActivity.onResume(ReactActivity.java:66)
       at android.app.Instrumentation.callActivityOnResume(Instrumentation.java:1269)
       at android.app.Activity.performResume(Activity.java:6786)
       at android.app.ActivityThread.performResumeActivity(ActivityThread.java:3407)
       at android.app.ActivityThread.handleResumeActivity(ActivityThread.java:3470)
       at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1528)
       at android.os.Handler.dispatchMessage(Handler.java:102)
       at android.os.Looper.loop(Looper.java:154)
       at android.app.ActivityThread.main(ActivityThread.java:6121)
       at java.lang.reflect.Method.invoke(Method.java)
       at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:889)
       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:779)

Please suggest a solution for same.

**Comment by gourav-singhal** [comment]
I am using 
react-native-calendar-events version 1.4.1 and
react-native version 0.45.1

Please suggest if there is any solution for same.

**Comment by wmcmahan** [comment]
@gourav-singhal Can you provide the call that you are making? My guess is that you may have missed the last part of the [Android setup](https://github.com/wmcmahan/react-native-calendar-events#android).

**Comment by gourav-singhal** [comment]
Thanks @wmcmahan I added the code for targetSDK is 23 or higher and it works fine.
Thanks for your valuable help and reply.

**Comment by gourav-singhal** [comment]
Facing the same issue in RN 0.55.4

**Comment by stigmat4j** [comment]
Bump problem. After click "Allow" on permission requst - app has crashed with error 
`E/AndroidRuntime: FATAL EXCEPTION: main
    Process: com.*, PID: 6982
    java.lang.RuntimeException: Unable to resume activity {com.*/com.*.MainActivity}: java.lang.NullPointerException: Attempt to invoke interface method 'void com.facebook.react.bridge.Callback.invoke(java.lang.Object[])' on a null object reference
`

RN version 0.60.3

**Comment by simonfranzen** [comment]
I have the problem @gourav-singhal described. I am getting this error

```
com.facebook.react.modules.permissions.PermissionsModule.onRequestPermissionsResult PermissionsModule.java:204
com.facebook.react.ReactActivityDelegate$1.invoke ReactActivityDelegate.java:196
com.facebook.react.ReactActivityDelegate.onResume ReactActivityDelegate.java:106
com.facebook.react.ReactActivity.onResume ReactActivity.java:64
android.app.Instrumentation.callActivityOnResume Instrumentation.java:1456
android.app.Activity.performResume Activity.java:7611
android.app.ActivityThread.performResumeActivity ActivityThread.java:4336
android.app.ActivityThread.handleResumeActivity ActivityThread.java:4394
android.app.servertransaction.ResumeActivityItem.execute ResumeActivityItem.java:51
android.app.servertransaction.TransactionExecutor.executeLifecycleState TransactionExecutor.java:145
android.app.servertransaction.TransactionExecutor.execute TransactionExecutor.java:70
android.app.ActivityThread$H.handleMessage ActivityThread.java:2155
android.os.Handler.dispatchMessage Handler.java:109
android.os.Looper.loop Looper.java:207
android.app.ActivityThread.main ActivityThread.java:7539
java.lang.reflect.Method.invoke Method.java
com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run RuntimeInit.java:524
com.android.internal.os.ZygoteInit.main ZygoteInit.java:958

```

It works ok on my simulator and Android 7, but this was Android 9 device.



I have done everything for Android setup. Here is my code:

```
onPressEvent(event) {
    const { intl } = this.props
    const { startDate, startTime, endDate, endTime, displayTitle, description, address, wholeDay } = event
    const startVal = moment(`${startDate}T${moment.utc(startTime, 'YYYY-MM-DD HH:mm:ss').format('HH:mm')}`)
    const endVal = endDate ? moment(`${endDate}T${moment.utc(endTime, 'YYYY-MM-DD HH:mm:ss').format('HH:mm')}`) : undefined
  
    RNCalendarEvents.authorizeEventStore().then((res) => {
      if (res === 'authorized') {
        let alertMessage = intl.formatMessage({ id: 'question-add-event' })
        if (wholeDay === 'true') {
          if (startVal.isSame(endVal, 'day')) {
            alertMessage = `${alertMessage}${displayTitle}\n${startVal.format('ll')}`
          } else {
            alertMessage = `${alertMessage}${displayTitle}\n${startVal.format('ll')} - ${endVal.format('ll')}`
          }
        } else {
          alertMessage = `${alertMessage}${displayTitle}\n${startVal.format('lll')}\n${endVal.format('lll')}`
        }

        Alert.alert(
          intl.formatMessage({ id: 'add-event' }),
          alertMessage,
          [
            {
              text: intl.formatMessage({ id: 'no' }),
              onPress: () => deviceLog.log('Cancel Pressed'),
              style: 'cancel',
            },
            {
              text: intl.formatMessage({ id: 'yes' }),
              onPress: () => {
                RNCalendarEvents.saveEvent(displayTitle, {
                  startDate: moment(startVal, 'YYYY-MM-DD HH:mm:ss').toISOString(),
                  endDate: moment(endVal, 'YYYY-MM-DD HH:mm:ss').toISOString(),
                  location: this.parseAddress(address),
                  notes: description,
                  allDay: wholeDay === 'true',
                }).then((args) => {
                  Alert.alert(intl.formatMessage({ id: 'event-added' }), '')
                }).catch((error) => {
                  Alert.alert(error, '')
                  deviceLog.log(error)
                })
              },
            },
          ],
          { cancelable: false },
        )
      } else {
        Alert.alert(intl.formatMessage({ id: 'hint' }), intl.formatMessage({ id: 'hint-add-event' }))
      }
    }).catch((error) => { deviceLog.log('error'); deviceLog.log(error) })
  }

```


After the permission is granted the app crashed and closes.

**Comment by Unforgiven-wanda** [comment]
Having the same issue.

**Comment by priisingh** [comment]
same issue on react-native-59.5
Android app crash after clicking on deny
FATAL EXCEPTION: main
    Process: sh.mobile.vh, PID: 31388
    java.lang.RuntimeException: Unable to resume activity {sh.mobile.vh/sh.mobile.vh.MainActivity}: java.lang.NullPointerException: Attempt to invoke interface method 'void com.facebook.react.bridge.Callback.invoke(java.lang.Object[])' on a null object reference
        at android.app.ActivityThread.performResumeActivity(ActivityThread.java:3790)
        at android.app.ActivityThread.handleResumeActivity(ActivityThread.java:3830)
        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1746)
        at android.os.Handler.dispatchMessage(Handler.java:105)
        at android.os.Looper.loop(Looper.java:164)
        at android.app.ActivityThread.main(ActivityThread.java:6944)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.Zygote$MethodAndArgsCaller.run(Zygote.java:327)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1374)
     Caused by: java.lang.NullPointerException: Attempt to invoke interface method 'void com.facebook.react.bridge.Callback.invoke(java.lang.Object[])' on a null object reference
        at com.facebook.react.modules.permissions.PermissionsModule.onRequestPermissionsResult(PermissionsModule.java:204)
        at com.facebook.react.ReactActivityDelegate$1.invoke(ReactActivityDelegate.java:196)
        at com.facebook.react.ReactActivityDelegate.onResume(ReactActivityDelegate.java:106)
        at com.facebook.react.ReactActivity.onResume(ReactActivity.java:64)
        at android.app.Instrumentation.callActivityOnResume(Instrumentation.java:1361)
        at android.app.Activity.performResume(Activity.java:7361)
        at android.app.ActivityThread.performResumeActivity(ActivityThread.java:3765)

**Comment by gopi-22** [comment]
Caused by: java.lang.NullPointerException: 
  at com.facebook.react.modules.permissions.PermissionsModule.onRequestPermissionsResult (PermissionsModule.java:207)
  at com.facebook.react.ReactActivityDelegate$2.invoke (ReactActivityDelegate.java:169)
  at com.facebook.react.ReactActivityDelegate.onResume (ReactActivityDelegate.java:100)
  at com.facebook.react.ReactActivity.onResume (ReactActivity.java:56)
  at android.app.Instrumentation.callActivityOnResume (Instrumentation.java:1567)
  at android.app.Activity.performResume (Activity.java:7952)
  at android.app.ActivityThread.performResumeActivity (ActivityThread.java:4313)


I'm getting crash here...but the permission module is read-only. I can't edit the PermissionsModule.java class.
Anyone can help with this.
Thanks in Advance.

**Comment by jacob-israel-turner** [comment]
Has anyone found a resolution to this issue?  I'm not actually crashing, but am never getting a response from `authorizeEventStore()`.

**Comment by MoOx** [comment]
Could you try 2.0.0 & check if situation is better? Please reopen an issue if necessary. Thanks!
