### ISSUE TITLE
Crash on android with option recurrenceRule

### ISSUE THREAD

**Issue by huyhq1993** [wmcmahan/react-native-calendar-events#146]
Error diplay:
java.lang.IllegalArgumentException: Cannot have both DTEND and DURATION in an event
        at android.database.DatabaseUtils.readExceptionFromParcel(DatabaseUtils.java:165)
        at android.database.DatabaseUtils.readExceptionFromParcel(DatabaseUtils.java:135)
        at android.content.ContentProviderProxy.insert(ContentProviderNative.java:476)
        at android.content.ContentResolver.insert(ContentResolver.java:1284)
        at com.calendarevents.CalendarEvents.addEvent(CalendarEvents.java:505)
        at com.calendarevents.CalendarEvents.access$100(CalendarEvents.java:38)
        at com.calendarevents.CalendarEvents$2.run(CalendarEvents.java:939)
        at java.lang.Thread.run(Thread.java:761)
<!-- android api 27
  "dependencies": {
    "react": "16.3.1",
    "react-native": "0.55.3",
    "react-native-calendar-events": "^1.5.0"
  },
issue when i save a event with option 'daily'. it crashed on android, ios is run well

**Comment by deepakdezire23** [comment]
With Recurrence rule there are few points that we need to keep in mind:
1. startDate: utcDateToString((any value),
          endDate: utcDateToString(any value),
          location: 'any value,
          recurrence: 'weekly',
          recurrenceRule: {
          occurrence: 1000,
        }}

**Comment by SonQBChau** [comment]
on Android, if the event is recurring, leave out the endDate and specify it in the recurrenceRule. 
This should be included in the docs or should be considered as a bug. 

This code will work:
{
startDate: utcDateToString((any value),
recurrence: 'weekly',
recurrenceRule: {
frequency: 'weekly',
endDate: utcDateToString(any value),
}}

**Comment by nmeri17** [comment]
Whoever is still maintaining this module should please explicitly specify in the docs that endDate should be moved into the recurrenceRule when that key is present. Has cost me a sour afternoon, after going through all issues referencing saveEvent without any success. I found this by going through each issue one after the other.  @SonQBChau Many thanks for rescuing me from this misery.
