### ISSUE TITLE
'boolean android.database.Cursor.moveToNext()' on a null object reference

### ISSUE THREAD

**Issue by star-heng** [wmcmahan/react-native-calendar-events#255]
### Environment

android : 5.1.1   OPPO R7 Plus
react-native: 0.59.9
react:  16.8.3
react-native-calendar-events: 1.7.1
```
java.lang.NullPointerException: Attempt to invoke interface method 'boolean android.database.Cursor.moveToNext()' on a null object reference
    at com.calendarevents.CalendarEvents.serializeEventCalendars(CalendarEvents.java:1076)
    at com.calendarevents.CalendarEvents.findEventCalendars(CalendarEvents.java:123)
    at com.calendarevents.CalendarEvents.access$000(CalendarEvents.java:44)
    at com.calendarevents.CalendarEvents$1.run(CalendarEvents.java:1179)
    at java.lang.Thread.run(Thread.java:818)
```

**Comment by Darkhorse-Fraternity** [comment]
me too
