### ISSUE TITLE
crash in android Q

### ISSUE THREAD

**Issue by Darkhorse-Fraternity** [wmcmahan/react-native-calendar-events#287]
crash in android Q (android 29)
### Environment

System:
    OS: macOS 10.15.1
    CPU: (16) x64 Intel(R) Core(TM) i9-9980HK CPU @ 2.40GHz
    Memory: 3.34 GB / 32.00 GB
    Shell: 5.7.1 - /bin/zsh
  Binaries:
    Node: 12.8.0 - /var/folders/bx/v5ml4kjj7cn6gmbdfy5g7wg00000gn/T/yarn--1575429296396-0.8833167521304606/node
    Yarn: 1.17.3 - /var/folders/bx/v5ml4kjj7cn6gmbdfy5g7wg00000gn/T/yarn--1575429296396-0.8833167521304606/yarn
    npm: 6.10.3 - /usr/local/bin/npm
    Watchman: 4.9.0 - /usr/local/bin/watchman
  SDKs:
    iOS SDK:
      Platforms: iOS 13.1, DriverKit 19.0, macOS 10.15, tvOS 13.0, watchOS 6.0
    Android SDK:
      API Levels: 23, 24, 25, 26, 27, 28, 29
      Build Tools: 28.0.3, 29.0.0, 29.0.2
      System Images: android-29 | Google APIs Intel x86 Atom, android-29 | Google Play Intel x86 Atom
      Android NDK: 20.0.5594570
  IDEs:
    Android Studio: 3.5 AI-191.8026.42.35.5977832
    Xcode: 11.1/11A1027 - /usr/bin/xcodebuild
  npmPackages:
    react: 16.9.0 => 16.9.0
    react-native: 0.61.5 => 0.61.5
✨  Done in 7.69s.
### Expected Behavior

2019-12-04 11:11:04.767 12824-13048/com.combo E/AndroidRuntime: FATAL EXCEPTION: Thread-20
    Process: com.combo, PID: 12824
    android.database.sqlite.SQLiteException
        at android.database.DatabaseUtils.readExceptionFromParcel(DatabaseUtils.java:184)
        at android.database.DatabaseUtils.readExceptionFromParcel(DatabaseUtils.java:140)
        at android.content.ContentProviderProxy.insert(ContentProviderNative.java:481)
        at android.content.ContentResolver.insert(ContentResolver.java:1828)
        at com.calendarevents.CalendarEvents.createRemindersForEvent(CalendarEvents.java:825)
        at com.calendarevents.CalendarEvents.addEvent(CalendarEvents.java:663)
        at com.calendarevents.CalendarEvents.access$200(CalendarEvents.java:44)
        at com.calendarevents.CalendarEvents$3.run(CalendarEvents.java:1227)
        at java.lang.Thread.run(Thread.java:919)
2019-12-04 11:11:04.768 10723-10740/? E/DatabaseUtils: Writing exception to parcel
    android.database.sqlite.SQLiteDoneException
        at android.database.sqlite.SQLiteConnection.nativeExecuteForLong(Native Method)
        at android.database.sqlite.SQLiteConnection.executeForLong(SQLiteConnection.java:691)
        at android.database.sqlite.SQLiteSession.executeForLong(SQLiteSession.java:654)
        at android.database.sqlite.SQLiteStatement.simpleQueryForLong(SQLiteStatement.java:109)
        at android.database.DatabaseUtils.longForQuery(DatabaseUtils.java:935)
        at android.database.DatabaseUtils.longForQuery(DatabaseUtils.java:923)
        at com.android.providers.calendar.CalendarDatabaseHelper.duplicateEvent(CalendarDatabaseHelper.java:3377)
        at com.android.providers.calendar.CalendarProvider2.insertInTransactionInner(CalendarProvider2.java:2550)
        at com.android.providers.calendar.CalendarProvider2.insertInTransaction(CalendarProvider2.java:2317)
        at com.android.providers.calendar.SQLiteContentProvider.insert(SQLiteContentProvider.java:100)
        at com.android.providers.calendar.CalendarProvider2.insert(CalendarProvider2.java:2290)
        at android.content.ContentProvider$Transport.insert(ContentProvider.java:309)
        at android.content.ContentProviderNative.onTransact(ContentProviderNative.java:154)
        at android.os.Binder.execTransactInternal(Binder.java:1021)
        at android.os.Binder.execTransact(Binder.java:994)

**Comment by ccksfh** [comment]
same here

**Comment by MoOx** [comment]
Please provide more informations, you didn't respected the template.
If you want us to work on a fix, we need a proper way to reproduce the bug, so we can safely find & commit a fix.

**Comment by kangfenmao** [comment]
Same issue

```log
android.database.sqlite.SQLiteException
	at android.database.DatabaseUtils.readExceptionFromParcel(DatabaseUtils.java:184)
	at android.database.DatabaseUtils.readExceptionFromParcel(DatabaseUtils.java:140)
	at android.content.ContentProviderProxy.insert(ContentProviderNative.java:481)
	at android.content.ContentResolver.insert(ContentResolver.java:1844)
	at com.calendarevents.CalendarEvents.createRemindersForEvent(CalendarEvents.java:825)
	at com.calendarevents.CalendarEvents.addEvent(CalendarEvents.java:663)
	at com.calendarevents.CalendarEvents.access$200(CalendarEvents.java:44)
	at com.calendarevents.CalendarEvents$3.run(CalendarEvents.java:1225)
	at java.lang.Thread.run(Thread.java:929)
```

![image](https://user-images.githubusercontent.com/8253512/88025310-adba6c80-cb66-11ea-936d-08fe55911697.png)

**Comment by MoOx** [comment]
A stack trace don't help. Please provide issue on how to reproduce.

**Comment by kangfenmao** [comment]
Maybe no permission @MoOx

**Comment by kangfenmao** [comment]
You need to agree the agreement before use calendar. @MoOx @Darkhorse-Fraternity 

This error disappeared when I logged into my Google account.

**Comment by MoOx** [comment]
Thanks for the info

**Comment by MoOx** [comment]
I closed as I don't see what we can do, if you have any idea, let us know

**Comment by zhuozp** [comment]
Not for the permission reason, It seems some devices the default calendar is not 1. Here should use with id 1, should query all and find the first on is the correct
![image](https://user-images.githubusercontent.com/6176229/122156870-70587f00-ce9c-11eb-93db-c0febbcde2c4.png)
