### ISSUE TITLE
app crashes

### ISSUE THREAD

**Issue by rohitb-iprogrammer** [wmcmahan/react-native-calendar-events#342]
this issue is coming for samsung mobile phones

Fatal Exception: android.database.sqlite.SQLiteException
near ")": syntax error (code 1 SQLITE_ERROR[1]): , while compiling: SELECT Instances.event_id AS event_id, title, description, begin, end, allDay, eventLocation, rrule, calendar_id, availability, hasAlarm, original_id, Instances.event_id AS event_id, duration, original_sync_id FROM Instances INNER JOIN view_events AS Events ON (Instances.event_id=Events._id) WHERE (begin<=? AND end>=?) AND (((begin >= 1610695206000) AND (end <= 1612031400000) AND (visible = 1) AND (eventStatus IS NOT 2) AND (calendar_id = )))

crashes :-
73%
samsung
12%
OPPO
4%
vivo
3%
Xiaomi
8%
Other (8)

plz look into this.

**Comment by wmcmahan** [comment]
Are these queries intending to search from a specific calendar, and are there appropriate read permissions the the calendar?

**Comment by MoOx** [comment]
The query seems to not have a calendar id (at the very end).
Please respect the issue template and provide code that leads to this error.

**Comment by deepakd-iprogrammer** [comment]
Thanks @MoOx, the passing of an empty calendar id value may be the possible cause here.
primary calendar id having type as "com.google" is fetched first using find calendar function and then the event is being tried to be saved on that particular calendar. Maybe some devices don't have "com.google" as a calendar installed. We will put a  fix for this and monitor if still the issue persists.

**Comment by MoOx** [comment]
@deepakd-iprogrammer Could you share the code you used that raised the exception so we can prevent this (or at least throw a more explicit exception)?
Where you using `calendarId: ""`?
The best thing to do, is to use a know calendar. So retrieve all calendars first, then save an event inside one of these.

**Comment by deepakd-iprogrammer** [comment]
first we tried to fetch a  single calander id from a list of available calanders-->

step 1)
  RNCalendarEvents.requestPermissions((readOnly = false)).then(evt => {
                if (evt == 'authorized') {
                    let breakAfterSingleCalanderEntry = false
                    let calanderId = ''
                    RNCalendarEvents.findCalendars().then(evt => {
                        evt.map((calenderValue) => {
                            if (Platform.OS == 'ios') {
                                if (calenderValue.isPrimary && !breakAfterSingleCalanderEntry) {
                                    calanderId = calenderValue.id
                                    breakAfterSingleCalanderEntry = true
                                }
                            } else {
                                if (calenderValue.isPrimary && calenderValue.type == "com.google" && !breakAfterSingleCalanderEntry) {
                                    calanderId = calenderValue.id
                                    breakAfterSingleCalanderEntry = true
                                }
                            }
                        })
                        }
                      }}


step 2) Then after getting calendar id we checked for all existing entries in that particular calander entry ----->

   RNCalendarEvents.fetchAllEvents(current_day.toISOString(), days.toISOString(), [calanderId]).then(evt => {

// steps done for adding the entry if it doesn't already exist in the calander id

})

**Comment by deepakd-iprogrammer** [comment]
@MoOx Same above  code but  getting this crash error for some devices-

2021-01-21 20:45:49.521 14722-15069/? E/AndroidRuntime: FATAL EXCEPTION: Thread-115
    Process: com.mventus.selfcare.activity, PID: 14722
    android.database.CursorWindowAllocationException: Could not create CursorWindow from Parcel due to error -12, process fd count=662
        at android.database.CursorWindow.nativeCreateFromParcel(Native Method)
        at android.database.CursorWindow.<init>(CursorWindow.java:173)
        at android.database.CursorWindow.<init>(CursorWindow.java:45)
        at android.database.CursorWindow$1.createFromParcel(CursorWindow.java:722)
        at android.database.CursorWindow$1.createFromParcel(CursorWindow.java:720)
        at android.database.BulkCursorDescriptor.readFromParcel(BulkCursorDescriptor.java:75)
        at android.database.BulkCursorDescriptor$1.createFromParcel(BulkCursorDescriptor.java:34)
        at android.database.BulkCursorDescriptor$1.createFromParcel(BulkCursorDescriptor.java:30)
        at android.content.ContentProviderProxy.query(ContentProviderNative.java:426)
        at android.content.ContentResolver.query(ContentResolver.java:951)
        at android.content.ContentResolver.query(ContentResolver.java:887)
        at android.content.ContentResolver.query(ContentResolver.java:843)
        at com.calendarevents.RNCalendarEvents.findAttendeesByEventId(RNCalendarEvents.java:301)
        at com.calendarevents.RNCalendarEvents.serializeEvent(RNCalendarEvents.java:1123)
        at com.calendarevents.RNCalendarEvents.serializeEvents(RNCalendarEvents.java:1043)
        at com.calendarevents.RNCalendarEvents.findEvents(RNCalendarEvents.java:396)
        at com.calendarevents.RNCalendarEvents.access$400(RNCalendarEvents.java:44)
        at com.calendarevents.RNCalendarEvents$5.run(RNCalendarEvents.java:1355)
        at java.lang.Thread.run(Thread.java:919)
2021-01-21 20:45:49.521 14722-15035/? E/AndroidRuntime: FATAL EXCEPTION: Thread-81
    Process: com.mventus.selfcare.activity, PID: 14722
    android.database.CursorWindowAllocationException: Could not create CursorWindow from Parcel due to error -12, process fd count=660
        at android.database.CursorWindow.nativeCreateFromParcel(Native Method)
        at android.database.CursorWindow.<init>(CursorWindow.java:173)
        at android.database.CursorWindow.<init>(CursorWindow.java:45)
        at android.database.CursorWindow$1.createFromParcel(CursorWindow.java:722)
        at android.database.CursorWindow$1.createFromParcel(CursorWindow.java:720)
        at android.database.BulkCursorDescriptor.readFromParcel(BulkCursorDescriptor.java:75)
        at android.database.BulkCursorDescriptor$1.createFromParcel(BulkCursorDescriptor.java:34)
        at android.database.BulkCursorDescriptor$1.createFromParcel(BulkCursorDescriptor.java:30)
        at android.content.ContentProviderProxy.query(ContentProviderNative.java:426)
        at android.content.ContentResolver.query(ContentResolver.java:951)
        at android.content.ContentResolver.query(ContentResolver.java:887)
        at android.content.ContentResolver.query(ContentResolver.java:843)
        at com.calendarevents.RNCalendarEvents.findReminderByEventId(RNCalendarEvents.java:891)
        at com.calendarevents.RNCalendarEvents.serializeEvent(RNCalendarEvents.java:1126)
        at com.calendarevents.RNCalendarEvents.serializeEvents(RNCalendarEvents.java:1043)
        at com.calendarevents.RNCalendarEvents.findEvents(RNCalendarEvents.java:396)
        at com.calendarevents.RNCalendarEvents.access$400(RNCalendarEvents.java:44)
        at com.calendarevents.RNCalendarEvents$5.run(RNCalendarEvents.java:1355)
        at java.lang.Thread.run(Thread.java:919)
2021-01-21 20:45:49.521 14722-14994/? E/AndroidRuntime: FATAL EXCEPTION: Thread-42
    Process: com.mventus.selfcare.activity, PID: 14722
    android.database.CursorWindowAllocationException: Could not create CursorWindow from Parcel due to error -12, process fd count=663
        at android.database.CursorWindow.nativeCreateFromParcel(Native Method)
        at android.database.CursorWindow.<init>(CursorWindow.java:173)
Edit

**Comment by wmcmahan** [comment]
@deepakd-iprogrammer Are you sure the calendar id is properly defined? The code provided looks like it could still potentially  provide and empty string as an id.

**Comment by deepakd-iprogrammer** [comment]
yes @wmcmahan that was indeed an issue but  we have fixed the empty calander id by enclosing the fetch  calendar events function in a if block -
  if(calanderId!=''){

.....calendar events fetch code

}

but now the above cursorWindow error is also reported for some devices.

**Comment by wmcmahan** [comment]
The error is potentially a memory issue. I will check into the cursors and see if there are any issues with closers. I would also suggest limiting the time span for finding events, or running `fetchAllEvents` within a loop, since this could cause memory to overflow.
